name: Build and Deploy Go Package

on:
  push:
    branches:
      - main # Replace with your main branch name
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.1' # Specify your desired Go version

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: go build -v ./... 

    - name: Test
      run: go test -v ./...

    - name: Login to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
